import React, { useState } from 'react';
import { Itinerary, ItineraryDay } from '../types';
import { saveLeadToGoogleSheet } from '../services/geminiService';

// Import icons
import FoodIcon from './icons/FoodIcon';
import HikeIcon from './icons/HikeIcon';
import CarIcon from './icons/CarIcon';
import BedIcon from './icons/BedIcon';
import SceneryIcon from './icons/SceneryIcon';
import CultureIcon from './icons/CultureIcon';
import ShoppingIcon from './icons/ShoppingIcon';
import WaterIcon from './icons/WaterIcon';
import DefaultIcon from './icons/DefaultIcon';
import PhoneIcon from './icons/PhoneIcon';
import WhatsAppIcon from './icons/WhatsAppIcon';
import AdjustIcon from './icons/AdjustIcon';
import Spinner from './Spinner';
import ItineraryImage from './ItineraryImage';

// Helper function to get an icon based on activity text
const getIconForActivity = (activity: string): React.ReactNode => {
  const lowerCaseActivity = activity.toLowerCase();
  const iconClass = "h-6 w-6 text-teal-300";

  if (/\b(eat|lunch|dinner|breakfast|food|cuisine|restaurant)\b/.test(lowerCaseActivity)) {
    return <FoodIcon className={iconClass} />;
  }
  if (/\b(hike|hiking|trek|walk|trail)\b/.test(lowerCaseActivity)) {
    return <HikeIcon className={iconClass} />;
  }
  if (/\b(drive|travel|journey|transfer|car|cab|road)\b/.test(lowerCaseActivity)) {
    return <CarIcon className={iconClass} />;
  }
  if (/\b(hotel|check-in|check in|rest|resort|lodge|stay)\b/.test(lowerCaseActivity)) {
    return <BedIcon className={iconClass} />;
  }
  if (/\b(sunrise|sunset|viewpoint|view|scenery|point|peak|lake|garden)\b/.test(lowerCaseActivity)) {
    return <SceneryIcon className={iconClass} />;
  }
  if (/\b(monastery|temple|culture|gumpa|stupa|chorten)\b/.test(lowerCaseActivity)) {
    return <CultureIcon className={iconClass} />;
  }
  if (/\b(shopping|market|bazaar|mall|shop)\b/.test(lowerCaseActivity)) {
    return <ShoppingIcon className={iconClass} />;
  }
  if (/\b(river|rafting|water|boating)\b/.test(lowerCaseActivity)) {
    return <WaterIcon className={iconClass} />;
  }
  return <DefaultIcon className={iconClass} />;
};

const ActivityItem: React.FC<{ text: string }> = ({ text }) => (
  <div className="flex items-start space-x-4">
    <div className="flex-shrink-0 mt-1">
      {getIconForActivity(text)}
    </div>
    <p className="text-gray-200">{text}</p>
  </div>
);

const DayCard: React.FC<{ day: ItineraryDay, isLast: boolean }> = ({ day, isLast }) => (
  <div className="relative pl-12 pb-10">
    {/* Timeline line */}
    {!isLast && <div className="absolute left-[22px] top-3 h-full w-0.5 bg-teal-500/50"></div>}

    {/* Timeline dot */}
    <div className="absolute left-3 top-2 flex h-4 w-4 items-center justify-center rounded-full bg-teal-500 ring-4 ring-gray-800">
    </div>

    {/* Card content */}
    <div className="bg-gray-900/70 backdrop-blur-lg rounded-xl shadow-2xl transform hover:scale-[1.02] transition-transform duration-300 border border-white/20 overflow-hidden">
      {day.imageQuery && <ItineraryImage query={day.imageQuery} title={day.title} />}
      <div className="p-6">
        <p className="text-sm font-semibold text-teal-300 mb-1">DAY {day.day}</p>
        <h3 className="text-2xl font-bold text-white mb-4">{day.title}</h3>
        <div className="space-y-4">
          {day.activities.map((activity, index) => (
            <ActivityItem key={index} text={activity} />
          ))}
        </div>
      </div>
    </div>
  </div>
);


const ItineraryDisplay: React.FC<{ itinerary: Itinerary; onReset: () => void; onAdjust: (adjustmentRequest: string) => void; }> = ({ itinerary, onReset, onAdjust }) => {
  const sortedDays = itinerary.days.sort((a, b) => a.day - b.day);
  const [phone, setPhone] = useState('');
  const [sendStatus, setSendStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const [isAdjusting, setIsAdjusting] = useState(false);
  const [adjustmentText, setAdjustmentText] = useState('');
  
  const formatItineraryForWhatsApp = (itinerary: Itinerary): string => {
    let message = `*${itinerary.title}*\n\n`;
    message += `${itinerary.summary}\n\n`;
    
    message += `*Your Day-by-Day Itinerary:*\n\n`;
    itinerary.days.sort((a, b) => a.day - b.day).forEach(day => {
      message += `*Day ${day.day}: ${day.title}*\n`;
      day.activities.forEach(activity => {
        message += `- ${activity}\n`;
      });
      message += `\n`;
    });
  
    if (itinerary.notes && itinerary.notes.length > 0) {
      message += `*Traveler's Notes:*\n`;
      itinerary.notes.forEach(note => {
        message += `- ${note}\n`;
      });
      message += `\n`;
    }
    
    message += `_Generated by Tourex AI._`;
    return encodeURIComponent(message);
  };

  const handleSendToWhatsApp = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmedPhone = phone.trim();
    if (!trimmedPhone.match(/^[+]?\d{10,15}$/)) {
        alert("Please enter a valid phone number with country code (e.g., 919876543210).");
        setSendStatus('error');
        setTimeout(() => setSendStatus('idle'), 3000);
        return;
    }
    
    setSendStatus('sending');
    
    const phoneForApi = trimmedPhone.replace('+', '');
    
    // Save lead to Google Sheet (fire and forget)
    await saveLeadToGoogleSheet(phoneForApi, itinerary);
  
    // Format and send to WhatsApp
    const formattedMessage = formatItineraryForWhatsApp(itinerary);
    const whatsappUrl = `https://wa.me/${phoneForApi}?text=${formattedMessage}`;
    window.open(whatsappUrl, '_blank', 'noopener,noreferrer');
    
    setSendStatus('sent');
    setTimeout(() => setSendStatus('idle'), 3000); // Reset button after 3 seconds
  };
  
  const handleAdjustSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (adjustmentText.trim()) {
      onAdjust(adjustmentText);
    }
  };


  return (
    <div className="w-full max-w-4xl mx-auto p-4 md:p-8 text-white">
      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-4 tracking-tight" style={{textShadow: '0 2px 4px rgba(0,0,0,0.5)'}}>{itinerary.title}</h1>
        <p className="text-lg text-gray-300 max-w-2xl mx-auto">{itinerary.summary}</p>
      </div>

      <div className="relative">
        {/* The main container for the timeline items */}
        {sortedDays.map((day, index) => (
          <DayCard key={day.day} day={day} isLast={index === sortedDays.length - 1} />
        ))}
      </div>

      {itinerary.notes && itinerary.notes.length > 0 && (
        <div className="bg-gray-900/70 backdrop-blur-lg rounded-xl shadow-2xl p-6 my-8 border border-white/20">
          <h3 className="text-2xl font-bold text-teal-300 mb-3">Traveler's Notes</h3>
          <ul className="list-disc list-inside space-y-2 text-gray-200">
            {itinerary.notes.map((note, index) => (
              <li key={index}>{note}</li>
            ))}
          </ul>
        </div>
      )}

      {/* WhatsApp Share Section */}
      <div className="bg-gray-900/70 backdrop-blur-lg rounded-xl shadow-2xl p-8 my-8 border border-white/20">
        <h3 className="text-2xl font-bold text-teal-300 mb-3">Get this plan on your phone!</h3>
        <p className="text-gray-300 mb-6">Enter your WhatsApp number (with country code) to receive this itinerary instantly.</p>
        <form onSubmit={handleSendToWhatsApp} className="flex flex-col sm:flex-row items-center gap-4">
          <div className="relative w-full sm:w-auto flex-grow">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <WhatsAppIcon className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type="tel"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="e.g. 919876543210"
              className="w-full bg-gray-800 border border-gray-600 rounded-lg text-white pl-10 pr-4 py-3 focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent transition duration-300"
              required
            />
          </div>
          <button
            type="submit"
            disabled={sendStatus === 'sending' || sendStatus === 'sent'}
            className="w-full sm:w-auto bg-green-500 text-white font-bold py-3 px-6 rounded-lg hover:bg-green-600 disabled:bg-gray-500 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center gap-2"
          >
            {sendStatus === 'sending' ? (
                <>
                <Spinner className="h-5 w-5" />
                <span>Sending...</span>
                </>
            ) : sendStatus === 'sent' ? (
                'Sent!'
            ) : sendStatus === 'error' ? (
                'Retry'
            ) : (
                'Send to WhatsApp'
            )}
          </button>
        </form>
        {sendStatus === 'sent' && <p className="text-green-400 text-sm mt-2 text-center sm:text-left">Check your WhatsApp! A new tab should have opened.</p>}
        {sendStatus === 'error' && <p className="text-red-400 text-sm mt-2 text-center sm:text-left">Please enter a valid number and try again.</p>}
      </div>
      
      {/* Booking Section */}
      <div className="bg-gradient-to-r from-teal-500/80 to-cyan-600/80 backdrop-blur-lg rounded-xl shadow-2xl p-8 my-8 border border-white/30 text-center">
        <h3 className="text-3xl font-bold text-white mb-4">Ready to Book Your Adventure?</h3>
        <p className="text-gray-100 mb-6 text-lg">Contact us to finalize your trip and get the best deals!</p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
            <div className="flex items-center gap-3 bg-white/20 px-6 py-3 rounded-full">
                <PhoneIcon className="h-6 w-6 text-white" />
                <span className="text-xl font-semibold text-white tracking-wider">8116413984</span>
            </div>
            <a
              href="tel:8116413984"
              className="bg-white text-teal-600 font-bold py-3 px-8 rounded-full hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-teal-500 focus:ring-white transition-all duration-300 transform hover:scale-105 shadow-lg"
            >
              Book Now
            </a>
        </div>
      </div>
      
      {/* Adjustment Section */}
      {isAdjusting && (
         <div className="bg-gray-900/70 backdrop-blur-lg rounded-xl shadow-2xl p-8 my-8 border border-white/20">
            <h3 className="text-2xl font-bold text-teal-300 mb-3">Refine Your Itinerary</h3>
            <p className="text-gray-300 mb-6">Tell us what you'd like to change, and we'll generate a new version of your plan.</p>
            <form onSubmit={handleAdjustSubmit}>
              <textarea
                value={adjustmentText}
                onChange={(e) => setAdjustmentText(e.target.value)}
                placeholder="e.g., 'Can you add a day trip to Mirik?' or 'Make the first two days more relaxed.'"
                className="w-full p-4 bg-gray-800 border-2 border-gray-600 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent transition duration-300 resize-none h-28 mb-4"
              />
              <div className="flex items-center gap-4">
                <button
                  type="submit"
                  disabled={!adjustmentText.trim()}
                  className="flex-1 bg-teal-500 text-white font-bold py-3 px-6 rounded-lg hover:bg-teal-600 disabled:bg-gray-500 disabled:cursor-not-allowed transition-all duration-300"
                >
                  Regenerate Itinerary
                </button>
                <button
                  type="button"
                  onClick={() => setIsAdjusting(false)}
                  className="flex-1 bg-gray-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-gray-700 transition-colors duration-300"
                >
                  Cancel
                </button>
              </div>
            </form>
         </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-12">
        <button
          onClick={() => setIsAdjusting(true)}
          className="w-full sm:w-auto flex items-center justify-center gap-2 bg-white/10 backdrop-blur-sm text-white font-bold py-3 px-8 rounded-full hover:bg-white/20 transition-all duration-300"
        >
          <AdjustIcon className="h-5 w-5"/>
          Adjust This Plan
        </button>
        <button
          onClick={onReset}
          className="w-full sm:w-auto bg-teal-500 text-white font-bold py-3 px-8 rounded-full hover:bg-teal-600 transition-all duration-300"
        >
          Plan a New Trip
        </button>
      </div>
    </div>
  );
};

export default ItineraryDisplay;